name: security-it-stack

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.7
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # disable security for simplicity
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:9.0.7
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  suricata:
    container_name: suricata
    image: jasonish/suricata:latest
    network_mode: host  # to capture network traffic directly
    cap_add:
      - NET_ADMIN
    volumes:
      - ./src/config/suricata:/etc/suricata
      - suricata_logs:/var/log/suricata
    command: ["/usr/bin/suricata", "-c", "/etc/suricata/suricata.yaml", "-i", "lo", "-v"] # monitor loopback

  syslog-ng:
    container_name: syslog-ng
    image: balabit/syslog-ng:latest
    volumes:
      - ./src/config/syslog-ng:/etc/syslog-ng
      - suricata_logs:/var/log/suricata:ro
      - nginx_logs:/var/log/nginx:ro
    depends_on:
      - elasticsearch

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/web:/usr/share/nginx/html:ro
      - ./src/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx

volumes:
  es_data:
    driver: local
  suricata_logs:
    driver: local
  nginx_logs:
    driver: local