%YAML 1.1
---
# Network interfaces
af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes

# Home network
vars:
  address-groups:
    HOME_NET: "192.168.0.0/16,10.0.0.0/8,172.16.0.0/12" # specifies internal/trusted networks (RFC1918 private address ranges)
    EXTERNAL_NET: "!$HOME_NET" # all IPs not in HOME_NET

# Port groups
port-groups:
  HTTP_PORTS: "80"
  SHELLCODE_PORTS: "!80"
  ORACLE_PORTS: 1521
  SSH_PORTS: 22
  DNP3_PORTS: 20000
  MODBUS_PORTS: 502
  FILE_DATA_PORTS: "[$HTTP_PORTS,110,143]"
  FTP_PORTS: 21

# Logging
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert
        - http
        - dns
        - tls

# Basic detection settings
detect:
  profile: medium
  custom-values:
    toclient-groups: 3
    toserver-groups: 25

# Threading
threading:
  set-cpu-affinity: no