%YAML 1.1
---

# === Réseau à surveiller ===
vars:
  address-groups:
    HOME_NET: "127.0.0.1"
    EXTERNAL_NET: "!$HOME_NET"

# === Interface de capture ===
af-packet:
  - interface: lo      # On écoute sur la loopback (localhost)
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes

# === Fichiers de règles ===
default-rule-path: /etc/suricata/rules
rule-files:
  - local.rules

# === Logs (EVE JSON) ===
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert
        - http
        - dns
        - tls
        - flow

logging:
  default-log-level: info

# === Liens vers les autres fichiers ===
classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config
thresholds-file: /etc/suricata/threshold.config

detect:
  profile: medium
